version: "3.7"
services:
    app:
        volumes:
            - ./:/usr/src/app
        command: /bin/bash deploy.dev.sh
        build: ./
        ports:
          - "3000:3000"
          - "3001:3001"
